import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

const config: Config = {
  title: 'EchoButler SDK',
  tagline: 'Mood intelligence, Stellar payments, and social wellness for any app',
  favicon: 'img/favicon.ico',

  future: {
    v4: true,
  },

  url: 'https://karanjadavi.github.io',
  baseUrl: '/echobutler-sdk/',

  organizationName: 'karanjadavi',
  projectName: 'echobutler-sdk',

  onBrokenLinks: 'throw',

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  plugins: [
    [
      'docusaurus-plugin-typedoc',
      {
        entryPoints: [
          '../packages/js/core/src/index.ts',
          '../packages/js/mood/src/index.ts',
          '../packages/js/react/src/index.tsx',
          '../packages/js/stellar/src/index.ts',
        ],
        tsconfig: '../tsconfig.json',
       out: 'docs/api/js',
        readme: 'none',
        validation: { notDocumented: true },
        treatValidationWarningsAsErrors: true,
        sidebar: {
          pretty: true,
        },
      },
    ],
  ],

  markdown: {
    mermaid: true,
  },

  themes: ['@easyops-cn/docusaurus-search-local', '@docusaurus/theme-mermaid'],

  presets: [
    [
      'classic',
      {
        docs: {
          lastVersion: 'current',
          sidebarPath: './sidebars.ts',
          editUrl: 'https://github.com/karanjadavi/echobutler-sdk/tree/main/docs-site/',
        },
        // Changelog RSS/Atom feed — Docusaurus blog plugin used purely as a
        // feed generator. The human-readable aggregate page lives at
        // /docs/changelog (generated by scripts/aggregate-changelogs.mjs).
        blog: {
          id: 'changelog',
          routeBasePath: 'changelog',
          path: './changelog-feed',
          blogTitle: 'EchoButler SDK Changelog',
          blogDescription:
            'Aggregated release notes for every EchoButler SDK package — JS/TS, Rust, Flutter, Swift, and Python.',
          blogSidebarTitle: 'Recent releases',
          blogSidebarCount: 'ALL',
          feedOptions: {
            type: ['rss', 'atom'],
            title: 'EchoButler SDK Changelog',
            description:
              'Aggregated release notes for every EchoButler SDK package.',
            copyright: `Copyright © ${new Date().getFullYear()} EchoButler SDK`,
            language: 'en',
            limit: 20,
          },
          showReadingTime: false,
          postsPerPage: 10,
        },
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    image: 'img/docusaurus-social-card.jpg',
    colorMode: {
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: 'EchoButler SDK',
      logo: {
        alt: 'EchoButler SDK Logo',
        src: 'img/logo.svg',
      },
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'tutorialSidebar',
          position: 'left',
          label: 'Docs',
        },
        {
          to: '/docs/changelog',
          label: 'Changelog',
          position: 'left',
        },
        {
          to: '/changelog',
          label: 'Release Feed',
          position: 'left',
        },
        {
          href: 'https://github.com/karanjadavi/echobutler-sdk',
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Docs',
          items: [
            {
              label: 'Introduction',
              to: '/docs/intro',
            },
            {
              label: 'Architecture',
              to: '/docs/architecture',
            },
            {
              label: 'Core Concepts',
              to: '/docs/core-concepts',
            },
            {
              label: 'Changelog',
              to: '/docs/changelog',
            },
          ],
        },
        {
          title: 'Community',
          items: [
            {
              label: 'GitHub Issues',
              href: 'https://github.com/karanjadavi/echobutler-sdk/issues',
            },
          ],
        },
        {
          title: 'More',
          items: [
            {
              label: 'GitHub',
              href: 'https://github.com/karanjadavi/echobutler-sdk',
            },
          ],
        },
      ],
      copyright: `Copyright   ${new Date().getFullYear()} EchoButler SDK. Built with Docusaurus.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
